"""
constants.py
Shared design constants for the Firearm Tracker GUI.
"""

# Colors
COLOR_BG_FRAME = "#FFFFFF"
COLOR_LABEL = "#333333"
COLOR_WHITE = "#FFFFFF"
COLOR_GRAY = "#D3D3D3"
COLOR_ERROR_BG = "#FFCDD2"
COLOR_ERROR_TEXT = "#D32F2F"
COLOR_UNIT = "#999999"

# Typography
FONT_FAMILY = "Roboto"
LABEL_FONT_SIZE = 12
UNIT_FONT_SIZE = 10
TITLE_FONT_SIZE = 16
BUTTON_FONT_SIZE = 12

# Window Geometry
LOGIN_WINDOW_WIDTH = 360
LOGIN_WINDOW_HEIGHT = 350
MAIN_WINDOW_WIDTH = 1350
MAIN_WINDOW_HEIGHT = 750

# Padding & Spacing
LOGIN_MAIN_PADDING = 12
MAIN_CONTAINER_PADDING = 10
TAB_PADDING = 15
LOGIN_ICON_SIZE = 60
BUTTON_PADX = 3
